export interface ChecklistItem {
  category: string;
  title: string;
  description?: string;
  weeksBeforeEvent?: number;
  priority: "high" | "medium" | "low";
}

export const CHECKLIST_TEMPLATES: Record<string, ChecklistItem[]> = {
  wedding: [
    // 12+ months
    { category: "venue", title: "set your budget", priority: "high", weeksBeforeEvent: 52 },
    { category: "venue", title: "create your guest list", priority: "high", weeksBeforeEvent: 52 },
    { category: "venue", title: "research and book ceremony venue", priority: "high", weeksBeforeEvent: 48 },
    { category: "venue", title: "research and book reception venue", priority: "high", weeksBeforeEvent: 48 },
    { category: "photography", title: "hire photographer", priority: "high", weeksBeforeEvent: 48 },
    { category: "photography", title: "hire videographer", priority: "high", weeksBeforeEvent: 48 },
    { category: "entertainment", title: "hire wedding band or DJ", priority: "high", weeksBeforeEvent: 40 },
    // 6-9 months
    { category: "catering", title: "hire caterer and finalize menu", priority: "high", weeksBeforeEvent: 36 },
    { category: "venue", title: "hire wedding planner or coordinator", priority: "high", weeksBeforeEvent: 36 },
    { category: "decor", title: "hire florist", priority: "high", weeksBeforeEvent: 32 },
    { category: "attire", title: "choose and order wedding dress", priority: "high", weeksBeforeEvent: 32 },
    { category: "catering", title: "book wedding cake", priority: "medium", weeksBeforeEvent: 28 },
    { category: "invitations", title: "design and order invitations", priority: "high", weeksBeforeEvent: 24 },
    // 3-5 months
    { category: "attire", title: "choose bridesmaid dresses", priority: "medium", weeksBeforeEvent: 20 },
    { category: "attire", title: "arrange groom and groomsmen attire", priority: "medium", weeksBeforeEvent: 20 },
    { category: "transportation", title: "book transportation (limo, shuttle)", priority: "medium", weeksBeforeEvent: 16 },
    { category: "invitations", title: "mail invitations", priority: "high", weeksBeforeEvent: 12 },
    { category: "catering", title: "finalize menu and dietary requirements", priority: "high", weeksBeforeEvent: 12 },
    { category: "attire", title: "first dress fitting", priority: "medium", weeksBeforeEvent: 12 },
    // 1-2 months
    { category: "invitations", title: "track RSVPs and finalize guest count", priority: "high", weeksBeforeEvent: 8 },
    { category: "decor", title: "finalize floral arrangements", priority: "medium", weeksBeforeEvent: 8 },
    { category: "entertainment", title: "create and submit song list to DJ/band", priority: "medium", weeksBeforeEvent: 6 },
    { category: "day_of", title: "create ceremony and reception run of show", priority: "high", weeksBeforeEvent: 6 },
    { category: "attire", title: "final dress fitting", priority: "high", weeksBeforeEvent: 4 },
    { category: "catering", title: "submit final guest count to caterer", priority: "high", weeksBeforeEvent: 3 },
    // Week of
    { category: "day_of", title: "confirm all vendors with final details", priority: "high", weeksBeforeEvent: 1 },
    { category: "day_of", title: "prepare payments and tip envelopes for vendors", priority: "high", weeksBeforeEvent: 1 },
    { category: "day_of", title: "pack emergency day-of kit", priority: "medium", weeksBeforeEvent: 1 },
    { category: "day_of", title: "rehearsal dinner", priority: "medium", weeksBeforeEvent: 0 },
  ],

  milestone_birthday: [
    { category: "venue", title: "decide on party format (home, venue, restaurant)", priority: "high", weeksBeforeEvent: 16 },
    { category: "venue", title: "create guest list", priority: "high", weeksBeforeEvent: 12 },
    { category: "venue", title: "book venue", priority: "high", weeksBeforeEvent: 12 },
    { category: "catering", title: "choose catering style (plated, buffet, cocktail)", priority: "high", weeksBeforeEvent: 10 },
    { category: "entertainment", title: "book entertainment (band, DJ, performer, comedian)", priority: "medium", weeksBeforeEvent: 10 },
    { category: "invitations", title: "design and send invitations", priority: "high", weeksBeforeEvent: 8 },
    { category: "decor", title: "choose theme and color palette", priority: "medium", weeksBeforeEvent: 8 },
    { category: "catering", title: "book caterer", priority: "high", weeksBeforeEvent: 8 },
    { category: "photography", title: "hire photographer", priority: "medium", weeksBeforeEvent: 8 },
    { category: "catering", title: "order custom birthday cake", priority: "high", weeksBeforeEvent: 6 },
    { category: "decor", title: "order decorations and centerpieces", priority: "medium", weeksBeforeEvent: 6 },
    { category: "invitations", title: "follow up with RSVPs", priority: "medium", weeksBeforeEvent: 3 },
    { category: "catering", title: "finalize guest count for caterer", priority: "high", weeksBeforeEvent: 2 },
    { category: "entertainment", title: "prepare speeches and toasts schedule", priority: "medium", weeksBeforeEvent: 2 },
    { category: "decor", title: "organize photo display or memory board", priority: "low", weeksBeforeEvent: 2 },
    { category: "day_of", title: "confirm all vendors", priority: "high", weeksBeforeEvent: 1 },
    { category: "day_of", title: "create run of show", priority: "high", weeksBeforeEvent: 1 },
    { category: "day_of", title: "assign a day-of point person", priority: "medium", weeksBeforeEvent: 1 },
    { category: "personal_touches", title: "prepare a video montage or slideshow", priority: "low", weeksBeforeEvent: 3 },
    { category: "personal_touches", title: "arrange surprise element or special entrance", priority: "low", weeksBeforeEvent: 2 },
  ],

  quinceanera: [
    { category: "venue", title: "set total budget", priority: "high", weeksBeforeEvent: 52 },
    { category: "venue", title: "book church / ceremony venue", priority: "high", weeksBeforeEvent: 48 },
    { category: "venue", title: "book reception hall", priority: "high", weeksBeforeEvent: 48 },
    { category: "attire", title: "choose and order quinceañera dress", priority: "high", weeksBeforeEvent: 40 },
    { category: "entertainment", title: "book DJ or band", priority: "high", weeksBeforeEvent: 36 },
    { category: "decor", title: "hire florist and choose flowers", priority: "medium", weeksBeforeEvent: 32 },
    { category: "photography", title: "hire photographer and videographer", priority: "high", weeksBeforeEvent: 32 },
    { category: "invitations", title: "design quinceañera invitations", priority: "high", weeksBeforeEvent: 24 },
    { category: "catering", title: "book caterer and finalize menu", priority: "high", weeksBeforeEvent: 20 },
    { category: "catering", title: "order quinceañera cake", priority: "high", weeksBeforeEvent: 16 },
    { category: "attire", title: "choose chambelanes and damas outfits", priority: "medium", weeksBeforeEvent: 20 },
    { category: "entertainment", title: "choreograph waltz and surprise dance", priority: "high", weeksBeforeEvent: 20 },
    { category: "invitations", title: "send invitations", priority: "high", weeksBeforeEvent: 12 },
    { category: "decor", title: "choose and order quinceañera crown and accessories", priority: "medium", weeksBeforeEvent: 12 },
    { category: "personal_touches", title: "prepare court of honor gifts", priority: "medium", weeksBeforeEvent: 8 },
    { category: "personal_touches", title: "create quinceañera video/photo montage", priority: "medium", weeksBeforeEvent: 6 },
    { category: "invitations", title: "finalize guest count", priority: "high", weeksBeforeEvent: 3 },
    { category: "day_of", title: "create detailed day-of timeline", priority: "high", weeksBeforeEvent: 2 },
    { category: "day_of", title: "confirm all vendors", priority: "high", weeksBeforeEvent: 1 },
    { category: "day_of", title: "rehearsal with court of honor", priority: "high", weeksBeforeEvent: 1 },
  ],

  baby_shower: [
    { category: "venue", title: "choose host and set date", priority: "high", weeksBeforeEvent: 12 },
    { category: "venue", title: "decide venue (home, restaurant, venue)", priority: "high", weeksBeforeEvent: 10 },
    { category: "invitations", title: "create guest list", priority: "high", weeksBeforeEvent: 10 },
    { category: "decor", title: "choose theme and color palette", priority: "medium", weeksBeforeEvent: 8 },
    { category: "invitations", title: "design and send invitations", priority: "high", weeksBeforeEvent: 6 },
    { category: "catering", title: "plan menu (finger foods, brunch, lunch)", priority: "high", weeksBeforeEvent: 6 },
    { category: "decor", title: "order decorations and balloons", priority: "medium", weeksBeforeEvent: 4 },
    { category: "catering", title: "order custom shower cake", priority: "high", weeksBeforeEvent: 4 },
    { category: "entertainment", title: "plan games and activities", priority: "medium", weeksBeforeEvent: 4 },
    { category: "personal_touches", title: "prepare guest book or memory activity", priority: "low", weeksBeforeEvent: 4 },
    { category: "personal_touches", title: "purchase prizes for games", priority: "low", weeksBeforeEvent: 3 },
    { category: "invitations", title: "confirm RSVPs and guest count", priority: "high", weeksBeforeEvent: 2 },
    { category: "catering", title: "confirm all food orders", priority: "high", weeksBeforeEvent: 1 },
    { category: "day_of", title: "set up venue 2-3 hours before", priority: "high", weeksBeforeEvent: 0 },
    { category: "personal_touches", title: "prepare gift opening area and trash bags", priority: "low", weeksBeforeEvent: 0 },
    { category: "personal_touches", title: "assign someone to take notes on gifts", priority: "medium", weeksBeforeEvent: 0 },
  ],

  corporate_event: [
    { category: "venue", title: "define event objectives and success metrics", priority: "high", weeksBeforeEvent: 24 },
    { category: "venue", title: "set budget and get approvals", priority: "high", weeksBeforeEvent: 20 },
    { category: "venue", title: "research and book venue", priority: "high", weeksBeforeEvent: 16 },
    { category: "venue", title: "arrange AV equipment and tech setup", priority: "high", weeksBeforeEvent: 12 },
    { category: "catering", title: "select catering and finalize F&B requirements", priority: "high", weeksBeforeEvent: 12 },
    { category: "invitations", title: "design and send invitations / registration", priority: "high", weeksBeforeEvent: 10 },
    { category: "entertainment", title: "confirm keynote speakers and agenda", priority: "high", weeksBeforeEvent: 10 },
    { category: "photography", title: "hire photographer and/or videographer", priority: "medium", weeksBeforeEvent: 8 },
    { category: "decor", title: "order branded materials and signage", priority: "medium", weeksBeforeEvent: 8 },
    { category: "invitations", title: "send reminder communications", priority: "high", weeksBeforeEvent: 4 },
    { category: "day_of", title: "create detailed run of show", priority: "high", weeksBeforeEvent: 4 },
    { category: "day_of", title: "brief all staff and assign roles", priority: "high", weeksBeforeEvent: 2 },
    { category: "transportation", title: "arrange parking and transportation logistics", priority: "medium", weeksBeforeEvent: 2 },
    { category: "day_of", title: "conduct venue walkthrough", priority: "high", weeksBeforeEvent: 1 },
    { category: "day_of", title: "confirm all vendor arrival times", priority: "high", weeksBeforeEvent: 1 },
    { category: "day_of", title: "prepare event-day emergency kit", priority: "medium", weeksBeforeEvent: 1 },
    { category: "personal_touches", title: "arrange speaker gifts and appreciation", priority: "low", weeksBeforeEvent: 1 },
    { category: "personal_touches", title: "prepare post-event survey", priority: "medium", weeksBeforeEvent: 1 },
    { category: "personal_touches", title: "arrange branded gifts or swag for attendees", priority: "low", weeksBeforeEvent: 2 },
  ],

  graduation: [
    { category: "venue", title: "decide venue (home, restaurant, park, hall)", priority: "high", weeksBeforeEvent: 12 },
    { category: "venue", title: "create guest list", priority: "high", weeksBeforeEvent: 10 },
    { category: "catering", title: "choose catering style", priority: "high", weeksBeforeEvent: 8 },
    { category: "invitations", title: "design and send invitations", priority: "high", weeksBeforeEvent: 6 },
    { category: "decor", title: "choose school colors and theme", priority: "medium", weeksBeforeEvent: 6 },
    { category: "catering", title: "order graduation cake", priority: "high", weeksBeforeEvent: 4 },
    { category: "decor", title: "order decorations and banners", priority: "medium", weeksBeforeEvent: 4 },
    { category: "photography", title: "arrange photographer or photo booth", priority: "medium", weeksBeforeEvent: 6 },
    { category: "personal_touches", title: "create photo display and memory board", priority: "low", weeksBeforeEvent: 3 },
    { category: "personal_touches", title: "organize graduation video montage", priority: "low", weeksBeforeEvent: 3 },
    { category: "invitations", title: "confirm RSVPs", priority: "high", weeksBeforeEvent: 2 },
    { category: "day_of", title: "confirm all arrangements", priority: "high", weeksBeforeEvent: 1 },
    { category: "personal_touches", title: "prepare thank you notes to mail after", priority: "low", weeksBeforeEvent: 0 },
  ],

  dinner_party: [
    { category: "venue", title: "set date and decide venue (home vs. restaurant)", priority: "high", weeksBeforeEvent: 4 },
    { category: "invitations", title: "invite guests and get RSVPs", priority: "high", weeksBeforeEvent: 3 },
    { category: "catering", title: "plan menu accounting for dietary restrictions", priority: "high", weeksBeforeEvent: 2 },
    { category: "decor", title: "choose table setting and ambiance theme", priority: "medium", weeksBeforeEvent: 2 },
    { category: "entertainment", title: "create dinner playlist", priority: "low", weeksBeforeEvent: 1 },
    { category: "catering", title: "shop for ingredients or confirm caterer", priority: "high", weeksBeforeEvent: 1 },
    { category: "decor", title: "arrange florals and table decor", priority: "medium", weeksBeforeEvent: 0 },
    { category: "catering", title: "prep as much food as possible in advance", priority: "high", weeksBeforeEvent: 0 },
    { category: "personal_touches", title: "create handwritten place cards", priority: "low", weeksBeforeEvent: 0 },
    { category: "personal_touches", title: "prepare a small favor or gift for guests", priority: "low", weeksBeforeEvent: 0 },
  ],

  default: [
    { category: "venue", title: "define event vision and goals", priority: "high", weeksBeforeEvent: 16 },
    { category: "venue", title: "set budget", priority: "high", weeksBeforeEvent: 14 },
    { category: "venue", title: "create guest list", priority: "high", weeksBeforeEvent: 12 },
    { category: "venue", title: "book venue", priority: "high", weeksBeforeEvent: 10 },
    { category: "catering", title: "arrange catering", priority: "high", weeksBeforeEvent: 8 },
    { category: "invitations", title: "design and send invitations", priority: "high", weeksBeforeEvent: 8 },
    { category: "entertainment", title: "book entertainment", priority: "medium", weeksBeforeEvent: 8 },
    { category: "photography", title: "hire photographer", priority: "medium", weeksBeforeEvent: 8 },
    { category: "decor", title: "plan decorations and theme", priority: "medium", weeksBeforeEvent: 6 },
    { category: "invitations", title: "confirm RSVPs", priority: "high", weeksBeforeEvent: 2 },
    { category: "day_of", title: "create run of show", priority: "high", weeksBeforeEvent: 2 },
    { category: "day_of", title: "confirm all vendors", priority: "high", weeksBeforeEvent: 1 },
    { category: "day_of", title: "day-of coordination", priority: "high", weeksBeforeEvent: 0 },
  ],
};

export function getChecklistForEventType(eventType: string): ChecklistItem[] {
  return CHECKLIST_TEMPLATES[eventType] || CHECKLIST_TEMPLATES.default;
}
