export interface ChecklistItem {
  category: string;
  title: string;
  description?: string;
  weeksBeforeEvent?: number;
  priority: "high" | "medium" | "low";
}

export const CHECKLIST_TEMPLATES: Record<string, ChecklistItem[]> = {
  wedding: [
    // 12+ months
    { category: "venue", title: "Set your budget", priority: "high", weeksBeforeEvent: 52 },
    { category: "guest_list", title: "Create your guest list", priority: "high", weeksBeforeEvent: 52 },
    { category: "venue", title: "Research and book ceremony venue", priority: "high", weeksBeforeEvent: 48 },
    { category: "venue", title: "Research and book reception venue", priority: "high", weeksBeforeEvent: 48 },
    { category: "photography", title: "Hire photographer", priority: "high", weeksBeforeEvent: 48 },
    { category: "photography", title: "Hire videographer", priority: "high", weeksBeforeEvent: 48 },
    { category: "entertainment", title: "Hire wedding band or DJ", priority: "high", weeksBeforeEvent: 40 },
    // 6-9 months
    { category: "catering", title: "Hire caterer and finalize menu", priority: "high", weeksBeforeEvent: 36 },
    { category: "vendors", title: "Hire wedding planner or coordinator", priority: "high", weeksBeforeEvent: 36 },
    { category: "decor", title: "Hire florist", priority: "high", weeksBeforeEvent: 32 },
    { category: "attire", title: "Choose and order wedding dress", priority: "high", weeksBeforeEvent: 32 },
    { category: "catering", title: "Book wedding cake", priority: "medium", weeksBeforeEvent: 28 },
    { category: "invitations", title: "Design and order invitations", priority: "high", weeksBeforeEvent: 24 },
    // 3-5 months
    { category: "attire", title: "Choose bridesmaid dresses", priority: "medium", weeksBeforeEvent: 20 },
    { category: "attire", title: "Arrange groom and groomsmen attire", priority: "medium", weeksBeforeEvent: 20 },
    { category: "transportation", title: "Book transportation (limo, shuttle)", priority: "medium", weeksBeforeEvent: 16 },
    { category: "invitations", title: "Mail invitations", priority: "high", weeksBeforeEvent: 12 },
    { category: "catering", title: "Finalize menu and dietary requirements", priority: "high", weeksBeforeEvent: 12 },
    { category: "attire", title: "First dress fitting", priority: "medium", weeksBeforeEvent: 12 },
    // 1-2 months
    { category: "rsvp", title: "Track RSVPs and finalize guest count", priority: "high", weeksBeforeEvent: 8 },
    { category: "decor", title: "Finalize floral arrangements", priority: "medium", weeksBeforeEvent: 8 },
    { category: "entertainment", title: "Create and submit song list to DJ/band", priority: "medium", weeksBeforeEvent: 6 },
    { category: "day_of", title: "Create ceremony and reception run of show", priority: "high", weeksBeforeEvent: 6 },
    { category: "attire", title: "Final dress fitting", priority: "high", weeksBeforeEvent: 4 },
    { category: "catering", title: "Submit final guest count to caterer", priority: "high", weeksBeforeEvent: 3 },
    // Week of
    { category: "day_of", title: "Confirm all vendors with final details", priority: "high", weeksBeforeEvent: 1 },
    { category: "day_of", title: "Prepare payments and tip envelopes for vendors", priority: "high", weeksBeforeEvent: 1 },
    { category: "day_of", title: "Pack emergency day-of kit", priority: "medium", weeksBeforeEvent: 1 },
    { category: "day_of", title: "Rehearsal dinner", priority: "medium", weeksBeforeEvent: 0 },
  ],

  milestone_birthday: [
    { category: "venue", title: "Decide on party format (home, venue, restaurant)", priority: "high", weeksBeforeEvent: 16 },
    { category: "guest_list", title: "Create guest list", priority: "high", weeksBeforeEvent: 12 },
    { category: "venue", title: "Book venue", priority: "high", weeksBeforeEvent: 12 },
    { category: "catering", title: "Choose catering style (plated, buffet, cocktail)", priority: "high", weeksBeforeEvent: 10 },
    { category: "entertainment", title: "Book entertainment (band, DJ, performer, comedian)", priority: "medium", weeksBeforeEvent: 10 },
    { category: "invitations", title: "Design and send invitations", priority: "high", weeksBeforeEvent: 8 },
    { category: "decor", title: "Choose theme and color palette", priority: "medium", weeksBeforeEvent: 8 },
    { category: "vendors", title: "Book caterer", priority: "high", weeksBeforeEvent: 8 },
    { category: "photography", title: "Hire photographer", priority: "medium", weeksBeforeEvent: 8 },
    { category: "catering", title: "Order custom birthday cake", priority: "high", weeksBeforeEvent: 6 },
    { category: "decor", title: "Order decorations and centerpieces", priority: "medium", weeksBeforeEvent: 6 },
    { category: "rsvp", title: "Follow up with RSVPs", priority: "medium", weeksBeforeEvent: 3 },
    { category: "catering", title: "Finalize guest count for caterer", priority: "high", weeksBeforeEvent: 2 },
    { category: "entertainment", title: "Prepare speeches and toasts schedule", priority: "medium", weeksBeforeEvent: 2 },
    { category: "decor", title: "Organize photo display or memory board", priority: "low", weeksBeforeEvent: 2 },
    { category: "day_of", title: "Confirm all vendors", priority: "high", weeksBeforeEvent: 1 },
    { category: "day_of", title: "Create run of show", priority: "high", weeksBeforeEvent: 1 },
    { category: "day_of", title: "Assign a day-of point person", priority: "medium", weeksBeforeEvent: 1 },
    { category: "personal_touches", title: "Prepare a video montage or slideshow", priority: "low", weeksBeforeEvent: 3 },
    { category: "personal_touches", title: "Arrange surprise element or special entrance", priority: "low", weeksBeforeEvent: 2 },
  ],

  quinceanera: [
    { category: "venue", title: "Set total budget", priority: "high", weeksBeforeEvent: 52 },
    { category: "venue", title: "Book church / ceremony venue", priority: "high", weeksBeforeEvent: 48 },
    { category: "venue", title: "Book reception hall", priority: "high", weeksBeforeEvent: 48 },
    { category: "attire", title: "Choose and order quinceanera dress", priority: "high", weeksBeforeEvent: 40 },
    { category: "entertainment", title: "Book DJ or band", priority: "high", weeksBeforeEvent: 36 },
    { category: "decor", title: "Hire florist and choose flowers", priority: "medium", weeksBeforeEvent: 32 },
    { category: "photography", title: "Hire photographer and videographer", priority: "high", weeksBeforeEvent: 32 },
    { category: "invitations", title: "Design quinceanera invitations", priority: "high", weeksBeforeEvent: 24 },
    { category: "catering", title: "Book caterer and finalize menu", priority: "high", weeksBeforeEvent: 20 },
    { category: "catering", title: "Order quinceanera cake", priority: "high", weeksBeforeEvent: 16 },
    { category: "attire", title: "Choose chambelanes and damas outfits", priority: "medium", weeksBeforeEvent: 20 },
    { category: "entertainment", title: "Choreograph waltz and surprise dance", priority: "high", weeksBeforeEvent: 20 },
    { category: "invitations", title: "Send invitations", priority: "high", weeksBeforeEvent: 12 },
    { category: "decor", title: "Choose and order quinceanera crown and accessories", priority: "medium", weeksBeforeEvent: 12 },
    { category: "personal_touches", title: "Prepare court of honor gifts", priority: "medium", weeksBeforeEvent: 8 },
    { category: "personal_touches", title: "Create quinceanera video/photo montage", priority: "medium", weeksBeforeEvent: 6 },
    { category: "rsvp", title: "Finalize guest count", priority: "high", weeksBeforeEvent: 3 },
    { category: "day_of", title: "Create detailed day-of timeline", priority: "high", weeksBeforeEvent: 2 },
    { category: "day_of", title: "Confirm all vendors", priority: "high", weeksBeforeEvent: 1 },
    { category: "day_of", title: "Rehearsal with court of honor", priority: "high", weeksBeforeEvent: 1 },
  ],

  baby_shower: [
    { category: "venue", title: "Choose host and set date", priority: "high", weeksBeforeEvent: 12 },
    { category: "venue", title: "Decide venue (home, restaurant, venue)", priority: "high", weeksBeforeEvent: 10 },
    { category: "guest_list", title: "Create guest list", priority: "high", weeksBeforeEvent: 10 },
    { category: "decor", title: "Choose theme and color palette", priority: "medium", weeksBeforeEvent: 8 },
    { category: "invitations", title: "Design and send invitations", priority: "high", weeksBeforeEvent: 6 },
    { category: "catering", title: "Plan menu (finger foods, brunch, lunch)", priority: "high", weeksBeforeEvent: 6 },
    { category: "decor", title: "Order decorations and balloons", priority: "medium", weeksBeforeEvent: 4 },
    { category: "catering", title: "Order custom shower cake", priority: "high", weeksBeforeEvent: 4 },
    { category: "entertainment", title: "Plan games and activities", priority: "medium", weeksBeforeEvent: 4 },
    { category: "personal_touches", title: "Prepare guest book or memory activity", priority: "low", weeksBeforeEvent: 4 },
    { category: "personal_touches", title: "Purchase prizes for games", priority: "low", weeksBeforeEvent: 3 },
    { category: "rsvp", title: "Confirm RSVPs and guest count", priority: "high", weeksBeforeEvent: 2 },
    { category: "catering", title: "Confirm all food orders", priority: "high", weeksBeforeEvent: 1 },
    { category: "day_of", title: "Set up venue 2-3 hours before", priority: "high", weeksBeforeEvent: 0 },
    { category: "personal_touches", title: "Prepare gift opening area", priority: "low", weeksBeforeEvent: 0 },
    { category: "personal_touches", title: "Assign someone to take notes on gifts", priority: "medium", weeksBeforeEvent: 0 },
  ],

  corporate_event: [
    { category: "venue", title: "Define event objectives and success metrics", priority: "high", weeksBeforeEvent: 24 },
    { category: "venue", title: "Set budget and get approvals", priority: "high", weeksBeforeEvent: 20 },
    { category: "venue", title: "Research and book venue", priority: "high", weeksBeforeEvent: 16 },
    { category: "audio_visual", title: "Arrange AV equipment and tech setup", priority: "high", weeksBeforeEvent: 12 },
    { category: "audio_visual", title: "Schedule AV dry-run and sound check", priority: "high", weeksBeforeEvent: 4 },
    { category: "presentations", title: "Collect slide decks from all speakers", priority: "high", weeksBeforeEvent: 4 },
    { category: "presentations", title: "Confirm presentation order and timing", priority: "high", weeksBeforeEvent: 2 },
    { category: "catering", title: "Select catering and finalize F&B requirements", priority: "high", weeksBeforeEvent: 12 },
    { category: "invitations", title: "Design and send invitations/registration", priority: "high", weeksBeforeEvent: 10 },
    { category: "guest_list", title: "Manage attendee registration list", priority: "high", weeksBeforeEvent: 8 },
    { category: "entertainment", title: "Confirm keynote speakers and agenda", priority: "high", weeksBeforeEvent: 10 },
    { category: "photography", title: "Hire photographer and/or videographer", priority: "medium", weeksBeforeEvent: 8 },
    { category: "scenery", title: "Order branded materials and signage", priority: "medium", weeksBeforeEvent: 8 },
    { category: "security", title: "Hire security personnel", priority: "medium", weeksBeforeEvent: 6 },
    { category: "security", title: "Create access list and check-in protocol", priority: "high", weeksBeforeEvent: 2 },
    { category: "rsvp", title: "Send reminder communications", priority: "high", weeksBeforeEvent: 4 },
    { category: "day_of", title: "Create detailed run of show", priority: "high", weeksBeforeEvent: 4 },
    { category: "day_of", title: "Brief all staff and assign roles", priority: "high", weeksBeforeEvent: 2 },
    { category: "transportation", title: "Arrange parking and transportation logistics", priority: "medium", weeksBeforeEvent: 2 },
    { category: "day_of", title: "Conduct venue walkthrough", priority: "high", weeksBeforeEvent: 1 },
    { category: "day_of", title: "Confirm all vendor arrival times", priority: "high", weeksBeforeEvent: 1 },
    { category: "vendors", title: "Confirm all vendor contracts and payments", priority: "high", weeksBeforeEvent: 2 },
    { category: "welcome_registration", title: "Set up registration/check-in area", priority: "high", weeksBeforeEvent: 0 },
    { category: "personal_touches", title: "Arrange speaker gifts and appreciation", priority: "low", weeksBeforeEvent: 1 },
    { category: "personal_touches", title: "Prepare post-event survey", priority: "medium", weeksBeforeEvent: 1 },
  ],

  graduation: [
    { category: "venue", title: "Decide venue (home, restaurant, park, hall)", priority: "high", weeksBeforeEvent: 12 },
    { category: "guest_list", title: "Create guest list", priority: "high", weeksBeforeEvent: 10 },
    { category: "catering", title: "Choose catering style", priority: "high", weeksBeforeEvent: 8 },
    { category: "invitations", title: "Design and send invitations", priority: "high", weeksBeforeEvent: 6 },
    { category: "decor", title: "Choose school colors and theme", priority: "medium", weeksBeforeEvent: 6 },
    { category: "catering", title: "Order graduation cake", priority: "high", weeksBeforeEvent: 4 },
    { category: "decor", title: "Order decorations and banners", priority: "medium", weeksBeforeEvent: 4 },
    { category: "photography", title: "Arrange photographer or photo booth", priority: "medium", weeksBeforeEvent: 6 },
    { category: "personal_touches", title: "Create photo display and memory board", priority: "low", weeksBeforeEvent: 3 },
    { category: "personal_touches", title: "Organize graduation video montage", priority: "low", weeksBeforeEvent: 3 },
    { category: "rsvp", title: "Confirm RSVPs", priority: "high", weeksBeforeEvent: 2 },
    { category: "day_of", title: "Confirm all arrangements", priority: "high", weeksBeforeEvent: 1 },
    { category: "personal_touches", title: "Prepare thank you notes to mail after", priority: "low", weeksBeforeEvent: 0 },
  ],

  dinner_party: [
    { category: "venue", title: "Set date and decide venue (home vs. restaurant)", priority: "high", weeksBeforeEvent: 4 },
    { category: "invitations", title: "Invite guests and get RSVPs", priority: "high", weeksBeforeEvent: 3 },
    { category: "catering", title: "Plan menu accounting for dietary restrictions", priority: "high", weeksBeforeEvent: 2 },
    { category: "decor", title: "Choose table setting and ambiance theme", priority: "medium", weeksBeforeEvent: 2 },
    { category: "entertainment", title: "Create dinner playlist", priority: "low", weeksBeforeEvent: 1 },
    { category: "catering", title: "Shop for ingredients or confirm caterer", priority: "high", weeksBeforeEvent: 1 },
    { category: "decor", title: "Arrange florals and table decor", priority: "medium", weeksBeforeEvent: 0 },
    { category: "catering", title: "Prep as much food as possible in advance", priority: "high", weeksBeforeEvent: 0 },
    { category: "personal_touches", title: "Create handwritten place cards", priority: "low", weeksBeforeEvent: 0 },
    { category: "personal_touches", title: "Prepare a small favor or gift for guests", priority: "low", weeksBeforeEvent: 0 },
  ],

  default: [
    { category: "venue", title: "Define event vision and goals", priority: "high", weeksBeforeEvent: 16 },
    { category: "venue", title: "Set budget", priority: "high", weeksBeforeEvent: 14 },
    { category: "guest_list", title: "Create guest list", priority: "high", weeksBeforeEvent: 12 },
    { category: "venue", title: "Book venue", priority: "high", weeksBeforeEvent: 10 },
    { category: "security", title: "Hire security personnel", priority: "medium", weeksBeforeEvent: 8 },
    { category: "security", title: "Create access list and check-in protocol", priority: "high", weeksBeforeEvent: 2 },
    { category: "vendors", title: "Confirm all vendor contracts", priority: "high", weeksBeforeEvent: 8 },
    { category: "catering", title: "Arrange catering", priority: "high", weeksBeforeEvent: 8 },
    { category: "catering", title: "Accommodate dietary restrictions", priority: "high", weeksBeforeEvent: 4 },
    { category: "invitations", title: "Design and send invitations", priority: "high", weeksBeforeEvent: 8 },
    { category: "rsvp", title: "Set RSVP deadline and track responses", priority: "high", weeksBeforeEvent: 6 },
    { category: "entertainment", title: "Book entertainment", priority: "medium", weeksBeforeEvent: 8 },
    { category: "audio_visual", title: "Schedule AV equipment and dry-run", priority: "high", weeksBeforeEvent: 4 },
    { category: "presentations", title: "Collect and organize presentations", priority: "medium", weeksBeforeEvent: 3 },
    { category: "photography", title: "Hire photographer", priority: "medium", weeksBeforeEvent: 8 },
    { category: "photography", title: "Create shot list and key moments", priority: "medium", weeksBeforeEvent: 2 },
    { category: "transportation", title: "Confirm parking and transport arrangements", priority: "medium", weeksBeforeEvent: 4 },
    { category: "scenery", title: "Finalize venue layout and decor delivery", priority: "medium", weeksBeforeEvent: 3 },
    { category: "decor", title: "Plan decorations and theme", priority: "medium", weeksBeforeEvent: 6 },
    { category: "welcome_registration", title: "Plan check-in and registration setup", priority: "high", weeksBeforeEvent: 2 },
    { category: "rsvp", title: "Confirm RSVPs and final headcount", priority: "high", weeksBeforeEvent: 2 },
    { category: "day_of", title: "Create run of show document", priority: "high", weeksBeforeEvent: 2 },
    { category: "day_of", title: "Distribute vendor contact sheet", priority: "high", weeksBeforeEvent: 1 },
    { category: "day_of", title: "Confirm all vendors", priority: "high", weeksBeforeEvent: 1 },
    { category: "day_of", title: "Weather contingency plan", priority: "medium", weeksBeforeEvent: 1 },
  ],
};

// Full pre-populated items for each new category (used when seeding a new event)
export const CATEGORY_DEFAULT_ITEMS: Record<string, Array<{ title: string; priority: "high" | "medium" | "low" }>> = {
  security: [
    { title: "Hire security personnel", priority: "high" },
    { title: "Brief security team", priority: "high" },
    { title: "Create access list", priority: "high" },
    { title: "Set up check-in protocol", priority: "high" },
    { title: "Emergency plan", priority: "high" },
    { title: "ID verification process", priority: "medium" },
    { title: "Restricted areas signage", priority: "medium" },
    { title: "First aid station", priority: "high" },
  ],
  audio_visual: [
    { title: "Sound check scheduled", priority: "high" },
    { title: "AV equipment tested", priority: "high" },
    { title: "Microphone check", priority: "high" },
    { title: "Projector/screen test", priority: "medium" },
    { title: "Lighting test", priority: "medium" },
    { title: "Backup equipment available", priority: "medium" },
    { title: "Technical support on site", priority: "high" },
    { title: "Dry-run completed", priority: "high" },
  ],
  presentations: [
    { title: "Slide decks collected from all speakers", priority: "high" },
    { title: "Presentation order confirmed", priority: "high" },
    { title: "Clicker/laser pointer available", priority: "medium" },
    { title: "Backup copies saved", priority: "high" },
    { title: "Speaker briefing completed", priority: "high" },
    { title: "Q&A format defined", priority: "medium" },
    { title: "Timer/prompter ready", priority: "medium" },
  ],
  vendors: [
    { title: "Contract signed", priority: "high" },
    { title: "Deposit paid", priority: "high" },
    { title: "Final payment scheduled", priority: "high" },
    { title: "Contact info confirmed", priority: "medium" },
    { title: "Arrival time confirmed", priority: "high" },
    { title: "Setup requirements communicated", priority: "medium" },
    { title: "Day-of contact assigned", priority: "high" },
  ],
  scenery: [
    { title: "Venue walkthrough completed", priority: "high" },
    { title: "Layout diagram approved", priority: "high" },
    { title: "Decor delivery scheduled", priority: "high" },
    { title: "Setup crew confirmed", priority: "high" },
    { title: "Floral arrangements ordered", priority: "medium" },
    { title: "Backdrop/stage design finalized", priority: "medium" },
    { title: "Signage ordered", priority: "medium" },
    { title: "Branding elements placed", priority: "medium" },
  ],
  entertainment: [
    { title: "Entertainment booked and confirmed", priority: "high" },
    { title: "Set list reviewed", priority: "medium" },
    { title: "Sound requirements communicated", priority: "high" },
    { title: "Performance schedule confirmed", priority: "high" },
    { title: "Green room/backstage needs arranged", priority: "medium" },
    { title: "Payment schedule set", priority: "high" },
  ],
  guest_list: [
    { title: "Guest list finalized", priority: "high" },
    { title: "Invitations sent", priority: "high" },
    { title: "RSVPs tracked", priority: "high" },
    { title: "Dietary restrictions collected", priority: "medium" },
    { title: "Seating chart created", priority: "medium" },
    { title: "Name badges/place cards ordered", priority: "medium" },
    { title: "VIP list confirmed", priority: "high" },
    { title: "Plus-ones confirmed", priority: "medium" },
  ],
  rsvp: [
    { title: "RSVP deadline set", priority: "high" },
    { title: "RSVP link/page created", priority: "high" },
    { title: "Reminder sent to non-responders", priority: "medium" },
    { title: "Final headcount confirmed", priority: "high" },
    { title: "Waitlist managed", priority: "medium" },
    { title: "Cancellations noted", priority: "medium" },
  ],
  photography: [
    { title: "Photographer/videographer booked", priority: "high" },
    { title: "Shot list created", priority: "high" },
    { title: "Key moments identified", priority: "high" },
    { title: "Photo release forms signed", priority: "medium" },
    { title: "Delivery timeline confirmed", priority: "medium" },
    { title: "Backup memory cards available", priority: "medium" },
  ],
  transportation: [
    { title: "Parking arrangements confirmed", priority: "high" },
    { title: "Shuttle/transport booked", priority: "medium" },
    { title: "Directions sent to guests", priority: "medium" },
    { title: "Valet arranged if needed", priority: "low" },
    { title: "Transportation for VIPs confirmed", priority: "high" },
  ],
  catering: [
    { title: "Menu finalized", priority: "high" },
    { title: "Dietary restrictions accommodated", priority: "high" },
    { title: "Serving timeline set", priority: "high" },
    { title: "Bartender/servers confirmed", priority: "high" },
    { title: "Equipment rentals arranged", priority: "medium" },
    { title: "Tastings completed", priority: "medium" },
  ],
  day_of: [
    { title: "Run-of-show document created", priority: "high" },
    { title: "Vendor contact sheet distributed", priority: "high" },
    { title: "Timeline confirmed with all vendors", priority: "high" },
    { title: "Emergency contacts listed", priority: "high" },
    { title: "Walkie-talkies/communication plan", priority: "medium" },
    { title: "Weather contingency plan", priority: "medium" },
  ],
  welcome_registration: [
    { title: "Registration table set up", priority: "high" },
    { title: "Check-in process confirmed", priority: "high" },
    { title: "Name badges prepared", priority: "medium" },
    { title: "Welcome materials ready", priority: "medium" },
    { title: "Greeter/host staff assigned", priority: "high" },
  ],
};

export function getChecklistForEventType(eventType: string): ChecklistItem[] {
  return CHECKLIST_TEMPLATES[eventType] || CHECKLIST_TEMPLATES.default;
}
