export interface TimelineTemplate {
  time: string; // relative: "T-12 months", "T-6 weeks" OR day-of: "4:00 PM"
  title: string; // lowercase
  description: string; // what this item is
  protocolNote: string; // WHY this timing matters — educational
  category: "setup" | "ceremony" | "reception" | "logistics" | "protocol";
  isRequired: boolean;
  offsetType?: "months" | "weeks" | "days" | "day-of";
  offsetValue?: number; // negative = before event
  dayOfHour?: number; // 0-23 for day-of items (relative to ceremony start or noon)
  dayOfMinute?: number;
  durationMinutes?: number;
}

// ─── WEDDING ────────────────────────────────────────────────────────────────

export const WEDDING_TEMPLATE: TimelineTemplate[] = [
  // Planning milestones
  {
    time: "T-12 months",
    title: "book venue & confirm date",
    description: "reserve ceremony and reception venues, finalize wedding date",
    protocolNote: "popular venues book 12-18 months out. locking in the date unlocks everything else on this list.",
    category: "logistics",
    isRequired: true,
    offsetType: "months",
    offsetValue: 12,
  },
  {
    time: "T-9 months",
    title: "hire photographer, caterer & florist",
    description: "secure key vendors for photography, catering, and floral design",
    protocolNote: "top photographers book out 12+ months. 9 months out is cutting it — don't wait longer.",
    category: "logistics",
    isRequired: true,
    offsetType: "months",
    offsetValue: 9,
  },
  {
    time: "T-8 months",
    title: "send save-the-dates",
    description: "mail save-the-date cards to all invited guests",
    protocolNote: "8 months gives guests — especially out-of-towners — time to book travel and arrange schedules.",
    category: "logistics",
    isRequired: true,
    offsetType: "months",
    offsetValue: 8,
  },
  {
    time: "T-6 months",
    title: "book officiant, DJ/band & hair + makeup",
    description: "confirm ceremony officiant, music entertainment, and beauty team",
    protocolNote: "officiants and in-demand DJs fill up fast. beauty teams often take 1 bride per day — book early.",
    category: "logistics",
    isRequired: true,
    offsetType: "months",
    offsetValue: 6,
  },
  {
    time: "T-4 months",
    title: "send formal invitations",
    description: "mail wedding invitations to all guests",
    protocolNote: "industry rule: invitations go out 6-8 weeks before the event. 4 months out captures destination guests and gives RSVP buffer.",
    category: "logistics",
    isRequired: true,
    offsetType: "months",
    offsetValue: 4,
  },
  {
    time: "T-6 weeks",
    title: "RSVP deadline",
    description: "cutoff date for guests to respond to invitation",
    protocolNote: "RSVP deadline 6 weeks out: caterers need final headcount 2 weeks before. this gives you 4 weeks to chase stragglers and confirm the final count.",
    category: "protocol",
    isRequired: true,
    offsetType: "weeks",
    offsetValue: 6,
  },
  {
    time: "T-2 weeks",
    title: "submit final headcount to caterer",
    description: "confirm exact guest count with catering team",
    protocolNote: "industry standard: caterers need 2 weeks to source, prep, and staff correctly. late counts lead to under/over ordering.",
    category: "logistics",
    isRequired: true,
    offsetType: "weeks",
    offsetValue: 2,
  },
  {
    time: "T-1 week",
    title: "rehearsal dinner",
    description: "walk through ceremony with wedding party, followed by dinner",
    protocolNote: "running the ceremony once removes day-of nerves, clarifies cues, and lets the wedding party feel the flow before guests arrive.",
    category: "ceremony",
    isRequired: true,
    offsetType: "weeks",
    offsetValue: 1,
  },
  // Day-of items (times relative to ceremony start)
  {
    time: "4-5 hours before",
    title: "bride & wedding party prep begins",
    description: "hair, makeup, and getting-ready process for bride and bridesmaids",
    protocolNote: "hair and makeup for a wedding party takes 30-45min per person. 4-5 hours for 6-8 people is the math — don't underestimate.",
    category: "setup",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: -270, // -4.5 hrs in minutes from ceremony
    durationMinutes: 270,
  },
  {
    time: "2 hours before",
    title: "groom & groomsmen prep begins",
    description: "groom and groomsmen get dressed and ready",
    protocolNote: "men's prep is faster but 2 hours allows for photos, calm, and first look if planned.",
    category: "setup",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: -120,
    durationMinutes: 90,
  },
  {
    time: "30 min before ceremony",
    title: "doors open, guests seated",
    description: "venue doors open, ushers seat arriving guests",
    protocolNote: "doors open 30min early so latecomers don't disrupt the processional. guests feel settled, not rushed.",
    category: "ceremony",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: -30,
    durationMinutes: 30,
  },
  {
    time: "ceremony start",
    title: "ceremony begins",
    description: "processional, vows, ring exchange, pronouncement",
    protocolNote: "ceremony length: 20-30min civil, 45-60min religious. coordinate with your officiant — long ceremonies without AC lose guests.",
    category: "ceremony",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 0,
    durationMinutes: 45,
  },
  {
    time: "cocktail hour",
    title: "cocktail hour begins",
    description: "guests enjoy drinks and passed appetizers while wedding party takes photos",
    protocolNote: "cocktail hour serves double duty: guests mingle and stay entertained while the wedding party completes formal photography. 60min is the sweet spot — longer and guests lose steam.",
    category: "reception",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 45,
    durationMinutes: 60,
  },
  {
    time: "reception opens",
    title: "reception room doors open",
    description: "guests invited to move into reception space and find their seats",
    protocolNote: "guests typically take 15-20min to settle. open the room before the grand entrance so seating is smooth.",
    category: "reception",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 105,
    durationMinutes: 15,
  },
  {
    time: "grand entrance",
    title: "grand entrance",
    description: "wedding party and couple introduced and enter reception",
    protocolNote: "the grand entrance sets the energy for the entire reception. a high-energy intro and walk-in song transforms the mood instantly.",
    category: "reception",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 120,
    durationMinutes: 10,
  },
  {
    time: "first dance",
    title: "first dance",
    description: "couple's first dance as married partners",
    protocolNote: "first dance immediately after the entrance keeps the energy high and transitions naturally into welcome toasts.",
    category: "reception",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 130,
    durationMinutes: 5,
  },
  {
    time: "welcome toast",
    title: "welcome toast",
    description: "host or best man welcomes guests and toasts the couple",
    protocolNote: "opening toast sets the tone. keep to 2 minutes — it's a warm-up, not a roast.",
    category: "reception",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 135,
    durationMinutes: 5,
  },
  {
    time: "dinner service",
    title: "dinner service begins",
    description: "first course served, dinner begins",
    protocolNote: "starting dinner within 20min of entering the reception prevents guests from getting hungry or restless. a fed guest is a happy guest.",
    category: "reception",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 140,
    durationMinutes: 90,
  },
  {
    time: "parent dances",
    title: "parent dances",
    description: "mother-son and father-daughter dances during or after dinner",
    protocolNote: "parent dances mid-dinner (after first course) give guests a moment to pause, watch, and feel — without breaking the food service rhythm.",
    category: "reception",
    isRequired: false,
    offsetType: "day-of",
    offsetValue: 160,
    durationMinutes: 10,
  },
  {
    time: "speeches",
    title: "toasts & speeches",
    description: "maid of honor, best man, and family speeches",
    protocolNote: "speeches after dinner: guests are settled, food is served, attention peaks. protocol: 2 minutes per speech maximum. brief is memorable — long is forgotten.",
    category: "reception",
    isRequired: false,
    offsetType: "day-of",
    offsetValue: 200,
    durationMinutes: 20,
  },
  {
    time: "cake cutting",
    title: "cake cutting",
    description: "couple cuts the wedding cake",
    protocolNote: "cake cutting signals to guests that dessert is coming and transitions the mood toward open dancing. don't cut too early — let dinner finish.",
    category: "reception",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 225,
    durationMinutes: 10,
  },
  {
    time: "open dancing",
    title: "open dancing begins",
    description: "dance floor opens for all guests",
    protocolNote: "open dancing immediately after cake cutting keeps the energy from dipping. the DJ's job starts here — trust them.",
    category: "reception",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 235,
    durationMinutes: 90,
  },
  {
    time: "last song",
    title: "last song announced",
    description: "DJ announces final song of the evening",
    protocolNote: "announcing the last song 10-15min before the end gives guests a chance to say goodbye and build toward the send-off moment.",
    category: "reception",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 315,
    durationMinutes: 5,
  },
  {
    time: "send-off",
    title: "couple's send-off",
    description: "guests line up for sparkler or petal send-off as couple departs",
    protocolNote: "the send-off is the final image — the one that makes it onto the invitation and Instagram. coordinate with photographer 30min before.",
    category: "ceremony",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 325,
    durationMinutes: 15,
  },
];

// ─── CORPORATE CONFERENCE / SUMMIT ──────────────────────────────────────────

export const CORPORATE_CONFERENCE_TEMPLATE: TimelineTemplate[] = [
  {
    time: "T-3 months",
    title: "confirm speakers & agenda",
    description: "finalize all speakers, topics, and session order",
    protocolNote: "speakers need 3 months minimum to prepare slides, travel, and talking points. last-minute confirmations lead to mediocre presentations.",
    category: "logistics",
    isRequired: true,
    offsetType: "months",
    offsetValue: 3,
  },
  {
    time: "T-6 weeks",
    title: "send attendee confirmations",
    description: "email confirmed agenda and logistics to all registered attendees",
    protocolNote: "attendees need 6 weeks to arrange travel and block calendars. sending earlier is better, never later.",
    category: "logistics",
    isRequired: true,
    offsetType: "weeks",
    offsetValue: 6,
  },
  {
    time: "T-1 week",
    title: "AV run-through with speakers",
    description: "test all AV equipment, slides, and mics with each speaker",
    protocolNote: "AV failures are the #1 conference disaster. one run-through eliminates 90% of tech problems.",
    category: "setup",
    isRequired: true,
    offsetType: "weeks",
    offsetValue: 1,
  },
  {
    time: "registration opens",
    title: "registration & check-in opens",
    description: "attendee registration desk opens, welcome bags distributed",
    protocolNote: "opening registration 90 minutes before start is the professional protocol. it allows check-in buffer and time to fix name badge issues without delaying the program.",
    category: "logistics",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: -90,
    durationMinutes: 90,
  },
  {
    time: "opening remarks",
    title: "welcome & opening remarks",
    description: "host welcomes attendees and sets the agenda",
    protocolNote: "opening remarks: 10 minutes maximum. use this time to set context, not deliver content. long intros lose the room before the keynote begins.",
    category: "protocol",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 0,
    durationMinutes: 10,
  },
  {
    time: "morning keynote",
    title: "morning keynote",
    description: "first keynote speaker presents",
    protocolNote: "keynote length: 45-60 minutes is the cognitive sweet spot. after 60 minutes without a break, attention and retention drop sharply.",
    category: "protocol",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 10,
    durationMinutes: 50,
  },
  {
    time: "first break",
    title: "morning break",
    description: "15-20 minute networking and refreshment break",
    protocolNote: "cognitive reset: the brain needs physical movement and social interaction every 60-90 minutes to maintain focus. skipping this break costs you the second session.",
    category: "logistics",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 60,
    durationMinutes: 20,
  },
  {
    time: "session 2",
    title: "morning session + Q&A",
    description: "second speaker or panel, followed by audience Q&A",
    protocolNote: "Q&A at the end of each session gives the audience agency and surfaces real questions. 15 minutes is enough — cut it if it dies.",
    category: "protocol",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 80,
    durationMinutes: 60,
  },
  {
    time: "networking lunch",
    title: "networking lunch",
    description: "90-minute lunch break for networking and meals",
    protocolNote: "90 minutes is the professional standard for a conference lunch. 60 minutes feels rushed; people don't network when they're rushing. 90 minutes pays for itself in hallway deals.",
    category: "logistics",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 140,
    durationMinutes: 90,
  },
  {
    time: "afternoon keynote",
    title: "afternoon keynote",
    description: "afternoon's main speaker presents",
    protocolNote: "the post-lunch slot is the graveyard of conferences. book your most dynamic speaker here, or use interactive format to fight the food coma.",
    category: "protocol",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 230,
    durationMinutes: 45,
  },
  {
    time: "panel discussion",
    title: "panel discussion + Q&A",
    description: "moderated panel of speakers, followed by audience Q&A",
    protocolNote: "panels benefit from a strong moderator with prepared questions. audiences disengage from panels that become monologues. keep panelists to 2-3 minutes per answer.",
    category: "protocol",
    isRequired: false,
    offsetType: "day-of",
    offsetValue: 275,
    durationMinutes: 60,
  },
  {
    time: "closing remarks",
    title: "closing remarks",
    description: "host wraps up the day, announces next steps or follow-ups",
    protocolNote: "closing remarks: 10 minutes maximum. summarize the 3 things you want people to remember. anything more and they'll forget everything.",
    category: "protocol",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 335,
    durationMinutes: 10,
  },
  {
    time: "networking reception",
    title: "networking reception",
    description: "post-conference cocktail reception for attendees and speakers",
    protocolNote: "the networking reception is often where the real conference happens. 90 minutes is ideal — long enough for meaningful conversations, short enough that it doesn't drag.",
    category: "reception",
    isRequired: false,
    offsetType: "day-of",
    offsetValue: 345,
    durationMinutes: 90,
  },
];

// ─── GALA / CHARITY EVENT ───────────────────────────────────────────────────

export const GALA_TEMPLATE: TimelineTemplate[] = [
  {
    time: "T-6 months",
    title: "secure venue, entertainment & keynote",
    description: "book venue, headline entertainment, and keynote or honoree",
    protocolNote: "gala venues and name entertainment book 6-12 months out. starting at 6 months is minimum for a first-class event.",
    category: "logistics",
    isRequired: true,
    offsetType: "months",
    offsetValue: 6,
  },
  {
    time: "T-8 weeks",
    title: "send invitations",
    description: "mail formal gala invitations to all guests",
    protocolNote: "8 weeks gives high-net-worth guests time to arrange calendars, attire, and RSVP. less than 6 weeks feels like an afterthought.",
    category: "logistics",
    isRequired: true,
    offsetType: "weeks",
    offsetValue: 8,
  },
  {
    time: "T-2 weeks",
    title: "confirm auction items & paddle numbers",
    description: "finalize all auction items, values, and bidder paddle assignments",
    protocolNote: "auction items need catalog print time and sponsor sign-off. last-minute additions create chaos at registration.",
    category: "logistics",
    isRequired: true,
    offsetType: "weeks",
    offsetValue: 2,
  },
  {
    time: "cocktail reception",
    title: "cocktail reception begins",
    description: "guests arrive to drinks, passed hors d'oeuvres, and silent auction",
    protocolNote: "cocktail reception 60-90 minutes before dinner serves two purposes: it absorbs late arrivals gracefully, and gets guests loosened up and generous before the ask.",
    category: "reception",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: -75,
    durationMinutes: 75,
  },
  {
    time: "doors open",
    title: "main hall doors open",
    description: "guests transition from cocktail reception to main event space",
    protocolNote: "opening the main hall creates a moment of reveal. the room should be complete — table settings, stage lighting, centerpieces — when guests walk in.",
    category: "setup",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 0,
    durationMinutes: 15,
  },
  {
    time: "welcome remarks",
    title: "welcome remarks",
    description: "executive director or board chair welcomes guests",
    protocolNote: "5 minutes maximum. use this to establish the why — the mission moment that frames the entire evening and primes guests for generosity.",
    category: "ceremony",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 15,
    durationMinutes: 5,
  },
  {
    time: "program & entertainment",
    title: "opening program or entertainment",
    description: "opening performance, video, or program segment",
    protocolNote: "a 5-8 minute impact video or performance before dinner sets emotional tone. this is your mission made visual — the moment that moves people.",
    category: "protocol",
    isRequired: false,
    offsetType: "day-of",
    offsetValue: 20,
    durationMinutes: 10,
  },
  {
    time: "dinner service",
    title: "first course & dinner service begins",
    description: "salad or first course served as program continues",
    protocolNote: "starting dinner early keeps energy up. a full room with empty plates gets restless. serve food while the program runs — it's not rude, it's professional.",
    category: "reception",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 30,
    durationMinutes: 30,
  },
  {
    time: "live auction / fund-a-need",
    title: "live auction or fund-a-need",
    description: "auctioneer leads live auction and direct giving appeal",
    protocolNote: "auction between courses captures peak attention — guests aren't distracted by plates arriving or leaving. this placement consistently outperforms end-of-dinner auctions by 20-30%.",
    category: "protocol",
    isRequired: false,
    offsetType: "day-of",
    offsetValue: 60,
    durationMinutes: 30,
  },
  {
    time: "main course",
    title: "main course served",
    description: "entree course served to all tables",
    protocolNote: "following the auction with the main course rewards guests — they gave, now they eat. the emotional arc works.",
    category: "reception",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 90,
    durationMinutes: 45,
  },
  {
    time: "keynote speaker",
    title: "keynote speaker",
    description: "featured speaker presents during or after main course",
    protocolNote: "speaker during main course means guests can listen while eating — no awkward pause. time them to finish as plates are cleared.",
    category: "ceremony",
    isRequired: false,
    offsetType: "day-of",
    offsetValue: 110,
    durationMinutes: 20,
  },
  {
    time: "live entertainment",
    title: "live entertainment",
    description: "band, performer, or entertainment act",
    protocolNote: "live entertainment after the program gives guests a reward — and keeps them at the event longer, which extends bar revenue and conversation.",
    category: "reception",
    isRequired: false,
    offsetType: "day-of",
    offsetValue: 145,
    durationMinutes: 45,
  },
  {
    time: "dessert & dancing",
    title: "dessert service & dancing",
    description: "dessert served, dance floor opens",
    protocolNote: "dessert + dancing is the closing act. this combination signals to guests that formalities are over — now it's a party.",
    category: "reception",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 190,
    durationMinutes: 60,
  },
  {
    time: "close",
    title: "event close",
    description: "final remarks, thank-you acknowledgments, guests depart",
    protocolNote: "announce closing time 15 minutes before the actual end. guests need transition time — an abrupt close feels disrespectful of their evening.",
    category: "protocol",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 250,
    durationMinutes: 10,
  },
];

// ─── COCKTAIL PARTY ──────────────────────────────────────────────────────────

export const COCKTAIL_PARTY_TEMPLATE: TimelineTemplate[] = [
  {
    time: "T-3 weeks",
    title: "send invitations",
    description: "send invitations to guests",
    protocolNote: "3 weeks is the minimum social notice for a cocktail party. less feels last-minute; more and people forget.",
    category: "logistics",
    isRequired: true,
    offsetType: "weeks",
    offsetValue: 3,
  },
  {
    time: "start time",
    title: "posted start time",
    description: "official invitation start time",
    protocolNote: "social protocol: guests arrive 15-30 minutes after the posted time. plan your first passed appetizers to begin 20 minutes in when critical mass arrives.",
    category: "protocol",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 0,
    durationMinutes: 0,
  },
  {
    time: "+20 min",
    title: "first passed appetizers",
    description: "first round of hors d'oeuvres circulated",
    protocolNote: "first 30 minutes are arrival time — passed apps when most guests have arrived keeps the energy from stalling. don't serve before the room fills.",
    category: "reception",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 20,
    durationMinutes: 30,
  },
  {
    time: "throughout",
    title: "bar service open",
    description: "full bar service throughout the event",
    protocolNote: "bar open from the moment the first guest arrives to the last goodbye. a closed bar kills a cocktail party.",
    category: "setup",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 0,
    durationMinutes: 0,
  },
  {
    time: "every 20-30 min",
    title: "circulate fresh bites",
    description: "new round of passed appetizers or small bites every 20-30 minutes",
    protocolNote: "circulating food every 20-30 minutes gives guests a reason to stay put and gives servers a chance to read the room. it also visually signals the host is attentive.",
    category: "reception",
    isRequired: false,
    offsetType: "day-of",
    offsetValue: 50,
    durationMinutes: 0,
  },
  {
    time: "posted end -15 min",
    title: "signal close",
    description: "subtly signal the event is winding down",
    protocolNote: "closing signals: slow the bar service, clear hors d'oeuvre trays, lower music slightly. this lets guests say goodbyes without an awkward announcement.",
    category: "protocol",
    isRequired: false,
    offsetType: "day-of",
    offsetValue: 105,
    durationMinutes: 15,
  },
  {
    time: "posted end +30 min",
    title: "natural close",
    description: "event ends naturally 30-45 minutes after posted closing time",
    protocolNote: "cocktail parties end 30-45 minutes after the posted close — this is social protocol. guests who are having fun stay; those who need to leave have cover. plan your venue rental accordingly.",
    category: "protocol",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 150,
    durationMinutes: 15,
  },
];

// ─── BIRTHDAY / MILESTONE CELEBRATION ───────────────────────────────────────

export const BIRTHDAY_TEMPLATE: TimelineTemplate[] = [
  {
    time: "T-4 weeks",
    title: "send invitations",
    description: "send invitations to guests",
    protocolNote: "4 weeks is the standard notice for a milestone celebration. for destination or large gatherings, 6-8 weeks.",
    category: "logistics",
    isRequired: true,
    offsetType: "weeks",
    offsetValue: 4,
  },
  {
    time: "T-2 weeks",
    title: "confirm final headcount",
    description: "finalize guest count with caterer and venue",
    protocolNote: "two weeks gives the caterer time to adjust quantities and staffing. surprises on the day of cost money and goodwill.",
    category: "logistics",
    isRequired: true,
    offsetType: "weeks",
    offsetValue: 2,
  },
  {
    time: "start time",
    title: "guests arrive",
    description: "guests arrive and are greeted",
    protocolNote: "build in 15-30 minutes of arrival buffer. the honoree should be present and visible — nothing worse than guests arriving before the birthday person.",
    category: "reception",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 0,
    durationMinutes: 30,
  },
  {
    time: "+15 min",
    title: "welcome drinks",
    description: "drinks and light welcome bites served as guests arrive",
    protocolNote: "welcome drinks serve a social function: they give early arrivals something to do while waiting for the room to fill. never let a guest stand idle with nothing in hand.",
    category: "reception",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 15,
    durationMinutes: 30,
  },
  {
    time: "+45 min",
    title: "activities or program",
    description: "structured activity, entertainment, or program begins",
    protocolNote: "structured activity 45 minutes in — when most guests have arrived — turns a gathering into an event. it gives people something to share and remember.",
    category: "protocol",
    isRequired: false,
    offsetType: "day-of",
    offsetValue: 45,
    durationMinutes: 30,
  },
  {
    time: "dinner / meal",
    title: "meal service begins",
    description: "dinner, brunch, or meal served",
    protocolNote: "meal timing depends on event length. for 3-4hr parties, eat at the midpoint. for longer celebrations, eat earlier to maintain energy.",
    category: "reception",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 75,
    durationMinutes: 60,
  },
  {
    time: "cake & toast",
    title: "cake & birthday toast",
    description: "birthday cake presented, candles lit, toast given",
    protocolNote: "the birthday moment should happen after dinner when guests are satisfied and present. pre-announce it 10 minutes before so no one is mid-conversation.",
    category: "ceremony",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 135,
    durationMinutes: 15,
  },
  {
    time: "dancing & mingling",
    title: "open dancing & mingling",
    description: "guests dance, mingle, and celebrate freely",
    protocolNote: "post-cake is the party's second wind. music up, lights down slightly, and let the room do the rest.",
    category: "reception",
    isRequired: false,
    offsetType: "day-of",
    offsetValue: 150,
    durationMinutes: 90,
  },
];

// ─── CONCERT / SHOW ──────────────────────────────────────────────────────────

export const CONCERT_TEMPLATE: TimelineTemplate[] = [
  {
    time: "T-3 months",
    title: "finalize lineup & production",
    description: "confirm all acts, production riders, and technical requirements",
    protocolNote: "production riders from headliners can be complex — 3 months gives production time to source, build, and rehearse without crisis.",
    category: "logistics",
    isRequired: true,
    offsetType: "months",
    offsetValue: 3,
  },
  {
    time: "T-1 week",
    title: "full technical rehearsal",
    description: "complete soundcheck and technical run-through with all acts",
    protocolNote: "a full tech rehearsal catches lighting cues, monitor mixes, and stage logistics that paper riders miss. non-negotiable for professional production.",
    category: "setup",
    isRequired: true,
    offsetType: "weeks",
    offsetValue: 1,
  },
  {
    time: "load-in",
    title: "production load-in & soundcheck",
    description: "crew loads equipment, stage is built, all acts soundcheck",
    protocolNote: "load-in typically takes 4-6 hours for a full concert production. doors cannot open until load-in is complete and all acts have checked.",
    category: "setup",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: -360,
    durationMinutes: 240,
  },
  {
    time: "doors open",
    title: "doors open to public",
    description: "venue opens for general audience entry",
    protocolNote: "doors open 90 minutes before showtime — this is industry standard. it allows load-in final checks, bar setup, and prevents crowd crush at the last minute.",
    category: "logistics",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: -90,
    durationMinutes: 90,
  },
  {
    time: "opener",
    title: "opening act",
    description: "opening/support act performs",
    protocolNote: "openers run 30-45 minutes — long enough to warm the crowd, short enough to keep anticipation for the headliner. don't let them run long; it pushes everything back.",
    category: "ceremony",
    isRequired: false,
    offsetType: "day-of",
    offsetValue: 0,
    durationMinutes: 40,
  },
  {
    time: "intermission",
    title: "intermission",
    description: "break between opener and headliner",
    protocolNote: "30-minute intermission is the industry standard. it allows stage changeover, bathroom runs, and bar surge. shorter feels rushed; longer loses crowd energy.",
    category: "logistics",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 40,
    durationMinutes: 30,
  },
  {
    time: "headliner",
    title: "headliner performs",
    description: "main act performs full set",
    protocolNote: "headliner sets run 90-120 minutes including encore. the encore is a choreographed moment — crowd calls them back, band returns. it's theater, and audiences love it.",
    category: "ceremony",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 70,
    durationMinutes: 100,
  },
  {
    time: "encore",
    title: "encore",
    description: "headliner returns for 1-2 encore songs",
    protocolNote: "encore protocol: band exits, audience cheers, band returns. this is theatrical convention — it gives the audience agency and turns the finale into a shared moment.",
    category: "ceremony",
    isRequired: false,
    offsetType: "day-of",
    offsetValue: 165,
    durationMinutes: 15,
  },
  {
    time: "venue clear",
    title: "venue begins clearing",
    description: "house lights up, crowd begins exiting",
    protocolNote: "venue needs 30-45 minutes to clear safely after a large show. coordinate with security and local ordinances on close-out time.",
    category: "logistics",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 180,
    durationMinutes: 30,
  },
];

// ─── BRUNCH ──────────────────────────────────────────────────────────────────

export const BRUNCH_TEMPLATE: TimelineTemplate[] = [
  {
    time: "T-2 weeks",
    title: "send invitations",
    description: "send invitations and confirm guest count",
    protocolNote: "2 weeks is appropriate for a brunch. brunch is intimate — smaller guest lists mean the notice can be shorter than formal dinners.",
    category: "logistics",
    isRequired: true,
    offsetType: "weeks",
    offsetValue: 2,
  },
  {
    time: "start time",
    title: "guests arrive",
    description: "guests arrive and are greeted",
    protocolNote: "brunch guests tend to arrive on time or early — it's a daytime event. have drinks ready the moment the first guest walks in.",
    category: "reception",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 0,
    durationMinutes: 20,
  },
  {
    time: "+5 min",
    title: "welcome drinks served",
    description: "mimosas, juice, coffee service begins",
    protocolNote: "mimosas or a signature welcome drink immediately upon arrival sets the celebratory tone. coffee service ensures non-drinkers feel equally welcomed.",
    category: "reception",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 5,
    durationMinutes: 25,
  },
  {
    time: "+30 min",
    title: "food service begins",
    description: "brunch spread or plated courses served",
    protocolNote: "brunch service starts 30 minutes in — when most guests have arrived. earlier service feels rushed; later and guests get hungry and restless.",
    category: "reception",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 30,
    durationMinutes: 60,
  },
  {
    time: "+60 min",
    title: "program or toasts (if applicable)",
    description: "brief program, speeches, or celebratory toasts",
    protocolNote: "mid-brunch toasts land well because guests are fed, relaxed, and still present. 1-2 minutes per toast maximum — keep it warm and brief.",
    category: "ceremony",
    isRequired: false,
    offsetType: "day-of",
    offsetValue: 60,
    durationMinutes: 15,
  },
  {
    time: "+90 min",
    title: "dessert & coffee",
    description: "dessert course and fresh coffee service",
    protocolNote: "dessert at 90 minutes signals the beginning of the end — it's the social cue that brunch is winding down, without an awkward announcement.",
    category: "reception",
    isRequired: false,
    offsetType: "day-of",
    offsetValue: 90,
    durationMinutes: 30,
  },
  {
    time: "+120 min",
    title: "natural close",
    description: "event winds down naturally as guests depart",
    protocolNote: "brunches typically run 2-2.5 hours. they're gentle events — no dramatic close needed. clear coffee cups and guests take the hint.",
    category: "protocol",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 120,
    durationMinutes: 30,
  },
];

// ─── NETWORKING EVENT ────────────────────────────────────────────────────────

export const NETWORKING_EVENT_TEMPLATE: TimelineTemplate[] = [
  {
    time: "T-2 weeks",
    title: "send invitations",
    description: "send professional invitations with clear value proposition",
    protocolNote: "networking events need clear 'why attend' messaging. send invitations 2 weeks out with names of confirmed attendees if possible — social proof drives RSVPs.",
    category: "logistics",
    isRequired: true,
    offsetType: "weeks",
    offsetValue: 2,
  },
  {
    time: "registration opens",
    title: "registration & name badges",
    description: "attendee check-in, name badges, and welcome",
    protocolNote: "name badges at networking events are non-negotiable — and include company/role. the faster people know who they're talking to, the faster real conversations happen.",
    category: "logistics",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: -15,
    durationMinutes: 15,
  },
  {
    time: "start",
    title: "open networking begins",
    description: "attendees network freely with drinks and light bites",
    protocolNote: "first 20-30 minutes of a networking event are high-anxiety for most attendees. circulating food gives people a physical action — going to the food table — that creates natural conversation openers.",
    category: "reception",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 0,
    durationMinutes: 30,
  },
  {
    time: "+30 min",
    title: "facilitated introductions or icebreaker",
    description: "structured introduction activity or facilitated networking round",
    protocolNote: "structured icebreaker at 30 minutes gives late arrivals time to settle and breaks the room out of cliques. '2-minute pitch your company to 3 new people' is simple and effective.",
    category: "protocol",
    isRequired: false,
    offsetType: "day-of",
    offsetValue: 30,
    durationMinutes: 20,
  },
  {
    time: "+50 min",
    title: "speaker or panel (optional)",
    description: "short featured speaker or panel discussion",
    protocolNote: "if including a speaker, 15-20 minutes maximum for networking events. a speaker gives attendees a shared reference point for post-talk conversation — it's a conversation catalyst.",
    category: "protocol",
    isRequired: false,
    offsetType: "day-of",
    offsetValue: 50,
    durationMinutes: 20,
  },
  {
    time: "+70 min",
    title: "free networking continues",
    description: "open networking resumes",
    protocolNote: "the best networking happens after structured segments. the speaker/activity breaks the ice — now let people connect naturally with new conversation hooks.",
    category: "reception",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 70,
    durationMinutes: 50,
  },
  {
    time: "+120 min",
    title: "close & wrap-up",
    description: "host wraps up, thanks attendees, announces next event",
    protocolNote: "closing with 'the next event is...' gives people a reason to stay connected and starts building community beyond a single gathering.",
    category: "protocol",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 120,
    durationMinutes: 10,
  },
];

// ─── AWARDS CEREMONY ─────────────────────────────────────────────────────────

export const AWARDS_CEREMONY_TEMPLATE: TimelineTemplate[] = [
  {
    time: "T-6 weeks",
    title: "send invitations",
    description: "send invitations to nominees, winners (if pre-selected), and guests",
    protocolNote: "awards ceremonies require 6 weeks minimum — nominees need to arrange travel, attire, and in some cases prepare remarks.",
    category: "logistics",
    isRequired: true,
    offsetType: "weeks",
    offsetValue: 6,
  },
  {
    time: "T-1 week",
    title: "finalize script & winner seals",
    description: "complete show script, lock award order, seal winner envelopes",
    protocolNote: "sealing winners one week out prevents leaks while giving production enough time to prepare graphics, video packages, and presenter briefings.",
    category: "logistics",
    isRequired: true,
    offsetType: "weeks",
    offsetValue: 1,
  },
  {
    time: "pre-show reception",
    title: "pre-show cocktail reception",
    description: "guests arrive to cocktail reception before ceremony",
    protocolNote: "pre-show reception serves three functions: it absorbs late arrivals, allows red carpet/photo moments, and gets nominees in the right emotional state before the ceremony starts.",
    category: "reception",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: -60,
    durationMinutes: 60,
  },
  {
    time: "doors open",
    title: "auditorium doors open",
    description: "guests take their seats for the ceremony",
    protocolNote: "open the auditorium 15 minutes before showtime — not before. early seating kills the energy before it builds. 15 minutes is enough to seat a full room.",
    category: "setup",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: -15,
    durationMinutes: 15,
  },
  {
    time: "opening",
    title: "show opens",
    description: "host opens the ceremony with welcome and housekeeping",
    protocolNote: "the opening sets the tone for the entire show. brief is better — 5 minutes maximum before the first award. audiences came for the awards, not the preamble.",
    category: "ceremony",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 0,
    durationMinutes: 5,
  },
  {
    time: "award categories",
    title: "award presentations begin",
    description: "presenters introduce categories, nominees, and announce winners",
    protocolNote: "each award segment: 2-3 minutes for presenter intro, nominee reel or reading, and winner announcement. budget 5-8 minutes per award including acceptance speech.",
    category: "ceremony",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 5,
    durationMinutes: 90,
  },
  {
    time: "intermission",
    title: "intermission (if needed)",
    description: "15-minute break for long ceremonies",
    protocolNote: "if the ceremony runs longer than 75 minutes, a 15-minute intermission is mandatory. a non-stop 2-hour show loses the audience completely in the second half.",
    category: "logistics",
    isRequired: false,
    offsetType: "day-of",
    offsetValue: 60,
    durationMinutes: 15,
  },
  {
    time: "keynote award",
    title: "lifetime achievement or keynote award",
    description: "the evening's most prestigious award, presented last",
    protocolNote: "save the biggest award for last. this is the crescendo — everything builds to it. presenting it first deflates everything that follows.",
    category: "ceremony",
    isRequired: false,
    offsetType: "day-of",
    offsetValue: 90,
    durationMinutes: 15,
  },
  {
    time: "close",
    title: "closing remarks",
    description: "host wraps up, thanks sponsors and guests",
    protocolNote: "closing remarks: 3 minutes maximum. thank the sponsors (they paid for this), acknowledge the nominees, and get people to the reception.",
    category: "ceremony",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 105,
    durationMinutes: 5,
  },
  {
    time: "post-show reception",
    title: "post-show reception & celebration",
    description: "winners celebrate, photos taken, networking reception",
    protocolNote: "the post-show reception is often more memorable than the ceremony. winners celebrate, photos happen, and the emotional high of the evening carries the room.",
    category: "reception",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 110,
    durationMinutes: 90,
  },
];

// ─── CORPORATE DINNER ────────────────────────────────────────────────────────

export const CORPORATE_DINNER_TEMPLATE: TimelineTemplate[] = [
  {
    time: "T-3 weeks",
    title: "send invitations",
    description: "send formal dinner invitations with dress code",
    protocolNote: "3 weeks is proper notice for a corporate dinner. including dress code prevents awkward moments — nothing derails executive confidence like being underdressed.",
    category: "logistics",
    isRequired: true,
    offsetType: "weeks",
    offsetValue: 3,
  },
  {
    time: "T-1 week",
    title: "confirm seating chart",
    description: "finalize seating arrangements and place cards",
    protocolNote: "strategic seating is the art form of corporate dinners. who sits next to whom drives conversations, deals, and relationships. don't leave it to chance.",
    category: "logistics",
    isRequired: true,
    offsetType: "weeks",
    offsetValue: 1,
  },
  {
    time: "cocktail reception",
    title: "pre-dinner cocktail reception",
    description: "guests arrive for pre-dinner drinks and introductions",
    protocolNote: "45-60 minute cocktail reception allows all guests to arrive without delaying dinner. it also creates informal conversation before the formal seating structure takes over.",
    category: "reception",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: -50,
    durationMinutes: 50,
  },
  {
    time: "guests seated",
    title: "guests called to dinner",
    description: "guests transition to dining room and are seated",
    protocolNote: "calling guests to dinner at a fixed time maintains the formality. 'whenever you're ready' leads to a 30-minute parade of late arrivals disrupting the table.",
    category: "setup",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 0,
    durationMinutes: 10,
  },
  {
    time: "welcome remarks",
    title: "welcome remarks & introductions",
    description: "host welcomes guests and makes key introductions",
    protocolNote: "brief welcome establishes the purpose of the gathering. if there are VIP guests, introduce them now — it contextualizes conversations for the rest of the evening.",
    category: "ceremony",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 10,
    durationMinutes: 5,
  },
  {
    time: "first course",
    title: "first course served",
    description: "appetizer or soup course served",
    protocolNote: "first course serves as social lubricant — guests have something to eat and a prop for conversation. start service within 10 minutes of seating.",
    category: "reception",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 15,
    durationMinutes: 30,
  },
  {
    time: "main course",
    title: "main course",
    description: "entree service",
    protocolNote: "main course is where the substantive conversation happens. a 45-minute main course gives enough time for relationship-building conversation.",
    category: "reception",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 45,
    durationMinutes: 45,
  },
  {
    time: "keynote or remarks",
    title: "featured remarks or presentation",
    description: "key speaker, business update, or featured presentation",
    protocolNote: "presenting between main course and dessert captures peak attention — guests are satisfied but not yet thinking about leaving. 15-20 minutes maximum.",
    category: "protocol",
    isRequired: false,
    offsetType: "day-of",
    offsetValue: 80,
    durationMinutes: 20,
  },
  {
    time: "dessert",
    title: "dessert & coffee",
    description: "dessert course served with coffee and tea",
    protocolNote: "dessert is the social transition — it signals the evening is entering its final phase. guests relax their guard slightly; some of the best conversations happen over dessert.",
    category: "reception",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 100,
    durationMinutes: 30,
  },
  {
    time: "close",
    title: "host closes evening",
    description: "host thanks guests, closes dinner formally",
    protocolNote: "a formal close by the host is good manners — it gives guests permission to leave without awkwardness. keep it to 2 minutes. 'thank you all for being here tonight' is enough.",
    category: "ceremony",
    isRequired: true,
    offsetType: "day-of",
    offsetValue: 130,
    durationMinutes: 5,
  },
];

// ─── TEMPLATE MAP ────────────────────────────────────────────────────────────

export const TIMELINE_TEMPLATES: Record<string, TimelineTemplate[]> = {
  wedding: WEDDING_TEMPLATE,
  corporate_conference: CORPORATE_CONFERENCE_TEMPLATE,
  conference: CORPORATE_CONFERENCE_TEMPLATE,
  summit: CORPORATE_CONFERENCE_TEMPLATE,
  gala: GALA_TEMPLATE,
  charity: GALA_TEMPLATE,
  fundraiser: GALA_TEMPLATE,
  cocktail_party: COCKTAIL_PARTY_TEMPLATE,
  cocktail: COCKTAIL_PARTY_TEMPLATE,
  birthday: BIRTHDAY_TEMPLATE,
  milestone: BIRTHDAY_TEMPLATE,
  anniversary: BIRTHDAY_TEMPLATE,
  concert: CONCERT_TEMPLATE,
  show: CONCERT_TEMPLATE,
  performance: CONCERT_TEMPLATE,
  brunch: BRUNCH_TEMPLATE,
  networking: NETWORKING_EVENT_TEMPLATE,
  networking_event: NETWORKING_EVENT_TEMPLATE,
  awards: AWARDS_CEREMONY_TEMPLATE,
  awards_ceremony: AWARDS_CEREMONY_TEMPLATE,
  corporate_dinner: CORPORATE_DINNER_TEMPLATE,
  dinner: CORPORATE_DINNER_TEMPLATE,
};

export function getTemplateForEventType(eventType: string): TimelineTemplate[] | null {
  const normalized = eventType.toLowerCase().replace(/[\s-]/g, "_");
  return TIMELINE_TEMPLATES[normalized] || null;
}

// ─── DATE CALCULATION ────────────────────────────────────────────────────────

export interface GeneratedTimelineItem {
  time_slot: string | null; // actual time HH:MM or null
  title: string;
  description: string;
  protocolNote: string;
  category: string;
  isRequired: boolean;
  displayDate: string; // human-readable: "June 14" or "4:30 PM"
  displayTime: string; // e.g. "T-6 weeks" or "4:30 PM"
  sort_order: number;
  duration_minutes: number | null;
}

function addMinutesToTime(baseHour: number, baseMinute: number, minutesOffset: number): { hour: number; minute: number } {
  const totalMinutes = baseHour * 60 + baseMinute + minutesOffset;
  let hour = Math.floor(totalMinutes / 60) % 24;
  if (hour < 0) hour += 24;
  const minute = ((totalMinutes % 60) + 60) % 60;
  return { hour, minute };
}

function formatTimeSlot(hour: number, minute: number): string {
  return `${String(hour).padStart(2, "0")}:${String(minute).padStart(2, "0")}`;
}

function formatDisplayTime(hour: number, minute: number): string {
  const ampm = hour >= 12 ? "pm" : "am";
  const displayHour = hour > 12 ? hour - 12 : hour === 0 ? 12 : hour;
  return `${displayHour}:${String(minute).padStart(2, "0")} ${ampm}`;
}

function formatDate(date: Date): string {
  return date.toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });
}

function formatShortDate(date: Date): string {
  return date.toLocaleDateString("en-US", { month: "short", day: "numeric" });
}

export function generateTimelineFromTemplate(
  template: TimelineTemplate[],
  eventDate: string, // YYYY-MM-DD
  eventTime?: string | null // HH:MM
): GeneratedTimelineItem[] {
  const [year, month, day] = eventDate.split("-").map(Number);
  const eventDateObj = new Date(year, month - 1, day);

  // Default ceremony/start time: 4:00 PM for weddings/galas, 9:00 AM for conferences
  let baseHour = 16;
  let baseMinute = 0;
  if (eventTime) {
    const [h, m] = eventTime.split(":").map(Number);
    baseHour = h;
    baseMinute = m;
  }

  const results: GeneratedTimelineItem[] = [];

  template.forEach((item, index) => {
    if (item.offsetType === "months" && item.offsetValue !== undefined) {
      const targetDate = new Date(year, month - 1 - item.offsetValue, day);
      results.push({
        time_slot: null,
        title: item.title,
        description: item.description,
        protocolNote: item.protocolNote,
        category: item.category,
        isRequired: item.isRequired,
        displayDate: formatDate(targetDate),
        displayTime: `T-${item.offsetValue} month${item.offsetValue === 1 ? "" : "s"} (${formatShortDate(targetDate)})`,
        sort_order: index,
        duration_minutes: item.durationMinutes || null,
      });
    } else if (item.offsetType === "weeks" && item.offsetValue !== undefined) {
      const targetDate = new Date(year, month - 1, day - item.offsetValue * 7);
      results.push({
        time_slot: null,
        title: item.title,
        description: item.description,
        protocolNote: item.protocolNote,
        category: item.category,
        isRequired: item.isRequired,
        displayDate: formatDate(targetDate),
        displayTime: `T-${item.offsetValue} week${item.offsetValue === 1 ? "" : "s"} (${formatShortDate(targetDate)})`,
        sort_order: index,
        duration_minutes: item.durationMinutes || null,
      });
    } else if (item.offsetType === "days" && item.offsetValue !== undefined) {
      const targetDate = new Date(year, month - 1, day - item.offsetValue);
      results.push({
        time_slot: null,
        title: item.title,
        description: item.description,
        protocolNote: item.protocolNote,
        category: item.category,
        isRequired: item.isRequired,
        displayDate: formatDate(targetDate),
        displayTime: `T-${item.offsetValue} day${item.offsetValue === 1 ? "" : "s"} (${formatShortDate(targetDate)})`,
        sort_order: index,
        duration_minutes: item.durationMinutes || null,
      });
    } else if (item.offsetType === "day-of" && item.offsetValue !== undefined) {
      const { hour, minute } = addMinutesToTime(baseHour, baseMinute, item.offsetValue);
      const timeSlot = formatTimeSlot(hour, minute);
      const displayTimeStr = formatDisplayTime(hour, minute);
      results.push({
        time_slot: timeSlot,
        title: item.title,
        description: item.description,
        protocolNote: item.protocolNote,
        category: item.category,
        isRequired: item.isRequired,
        displayDate: `${formatShortDate(eventDateObj)} — ${displayTimeStr}`,
        displayTime: displayTimeStr,
        sort_order: index,
        duration_minutes: item.durationMinutes || null,
      });
    }
  });

  return results;
}
