ALTER TABLE events ADD COLUMN IF NOT EXISTS slug TEXT UNIQUE;
ALTER TABLE events ADD COLUMN IF NOT EXISTS landing_description TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS landing_image_url TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS dress_code TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS is_public BOOLEAN DEFAULT FALSE;
ALTER TABLE events ADD COLUMN IF NOT EXISTS agenda JSONB DEFAULT '[]';
